### PR TITLE
feature(issue#52): added a new dropdown component

### PR DESCRIPTION
**Pull request by KiranMantha**
Added a css only dropdown with reference to [issue#52](https://github.com/picocss/pico/issues/52)

### CODE REVIEW

**Comment by KiranMantha** [comment]
Please find the working implementation on my [stackblitz](https://stackblitz.com/edit/web-platform-vz6n19?file=index.html)

**Comment by lucaslarroche** [comment]
Thank you @KiranMantha, this is awesome.

Quick review:
- We should use a proper aria role as `dropdown` in not listed as an [official arial role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles): probably [list role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/list_role)
- The `<summary>` should have `aria-haspopup="listbox"` ([see here](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html))
- The list (`<ul>`) should have `role="listbox"` and as a result we should avoid the `<div>` wrapper around the `<ul>`
- We should avoid the unnecessary indent in the code example and use the classic HTML comment syntax (`<!-- -->`) syntax ([example here](https://github.com/picocss/pico/blob/master/docs/src/forms.html#L46))

I don't have time to make these changes for the next release (v1.4.3). 
It could be merged in the next one (v1.4.4).

**Comment by KiranMantha** [comment]
Thanks alot @lucaslarroche , i updated the code base. please check once.

**Comment by lucaslarroche** [comment]
Thank you, that was quick. Nice.

We still need to slightly adapt the styles ([height](https://github.com/picocss/pico/blob/master/scss/content/_form.scss#L113), [padding](https://github.com/picocss/pico/blob/master/scss/content/_form.scss#L146), [border-width](https://github.com/picocss/pico/blob/master/scss/content/_form-checkbox-radio.scss#L18), etc.)
I would like this new component to have the same styles as the default `<select>`.

I also would prefer to keep the native checkbox/radio element (to avoid using `::before`).
We probably just need to use this syntax :
```HTML
<label>
  <!-- Radio or Checkbox -->
  <input type="radio"> 
  Label
</label>
```

And not:
```HTML
<!-- Radio or Checkbox -->
<input type="radio">
<label>Label</label>
```
This way we can reduce the code in `_dropdown.scss`

I can take care of these changes.
I still think I will not merge this in the next release as I want to take more time to tweak the styles and probably slightly rewrite the documentation.

This PR will be merged, for sure.

**Comment by KiranMantha** [comment]
@lucaslarroche i made few changes to dropdown component to make it more inline with form controls. And i found one issue  where article tag has overflow hidden and when any element inside it has z-index then that element is not displaying as intended.

The best example is above dropdown where the options list has z-index but article has overflow hidden. when the dropdown is expanded then list is hidden behind article. I removed overflow on article. Please check it once.

**Comment by lucaslarroche** [comment]
To allow the Dropdown to be styled as a `<select>` or a `<button>`, I changed the behavior of the Accordion (`<details>`) components 

See #137

**Pull request merged**
