### PR TITLE
v1.5.0

### PR DESCRIPTION
**Pull request by lucaslarroche**
## v1.5.0

Preview: https://picocss.github.io/pico/docs/

### Feature
- Add Dropdown component, with a huge help from @KiranMantha and @ethanpil
#52 #85 #86 #106 #140 9a0db7a

### Improvements
- Add CSS vars for the `nav` component, spotted by @cara-tm
#99 #165  9b0dda8
- Minimal support for buttons and forms elements in the `nav` component, spotted by @nitodico
#162 #165
- Update sanitize.css resets
#169
- Optimize CSS selectors with `:where()` and `:is()` `(2)`, by @leomp12
#141 
- Add support for `<fieldset disabled>`, spotted by @Gaubee
#143 #170

### Fix
- Remove `overflow: hidden;` for Card (`<article>`) , by @KiranMantha, spotted by @Manuel-Steinberg and @prologic
#86 #156 #163

### Accessibility
- Inverse undetermined animation for the progress bar in RTL, spotted by @X7md
https://github.com/picocss/examples/pull/5 #154
- Add a minimal support for `aria-current` for links (`<a>`) and `<button>`, spotted by @marek-lach
#124 #166
- RTL support for input search, by @hayatbiralem
#173 #174

### Styles
- Styling tweaks for the `nav` component `(2)`, spotted by @cara-tm
#99 #165
- Better nested lists
#141 
- Better Accordion (`<details>`) margins
#165 6cbc258

### Documentation
- Remove duplicate label in the forms page, by @reinerBa
#142
- Add Dropdown documentation, with the help of @KiranMantha
#52 #85 #86 #106 #140 9a0db7a
- Add example for `role="button"` inside the `nav` component
#165  43cacb0
- Store color scheme in localStorage  
#158 8c64ef2
- Add explicit Browser support  
#76 066ecb4 e414757
- Add contributing guidelines, by @tusharnankani
#89 #111
- Add disclaimer about modal utility classes in the class-less version, by @sponsfreixes
#160 #172

**Notes**

`(1)`: CSS files are about 8% smaller with these improvements

`(2)`: Even if it is [debatable](https://medium.com/eightshapes-llc/visual-breaking-change-in-design-systems-1e9109fac9c4), we considered that this visual change did not constitute a breaking change.
That is why we publish this change as a [MINOR release](https://semver.org/) (_vs._ MAJOR release).
To bring back the old style, you can override the CSS vars as follows:

```CSS
:root {
  --nav-link-spacing-vertical: 1rem;
}
```

### CODE REVIEW

**Comment by Anachron** [comment]
Looks good!

Just a little heads up:
The nav dropdown has a bad newline wrap, which the "li role=list" doesnt have.

FF Mobile, 97.2.0 (Build #2015863827)

**Comment by lucaslarroche** [comment]
Thank you@Anachron, 
Can you give more detail? Or a screenshot? I'm not sure what problem you are talking about.

**Comment by Anachron** [comment]
Sure. 

See

Screenshot_20220228-105205_Firefox

Vs

Screenshot_20220228-105213_Firefox

Sorry for the lacking reply, I was on mobile and my github mobile app didnt allow file uploads on comment fields, so I logged in to the web client.

**Comment by lucaslarroche** [comment]
That is helpful.
It's definitively a bug. It's fixed. 
Preview here: https://picocss.github.io/pico/docs/dropdowns.html

**Comment by Anachron** [comment]
Yep, after a forced refresh on mobile everything works now as expected.

Thanks for the quick fix.

I'm planning to do more testing on picocss and also contribute to it.

**Comment by Anachron** [comment]
Is there any reason why the nav dropdown is bigger than the link? (See below)

Screenshot_20220228-211954_Firefox

It doesnt look good imo.

Also the default dropdown padding feels a bit too much for my taste. (At least on mobile)

Screenshot_20220228-212644_Firefox

The dropdown component is quite big. Maybe we can split it up (later?) and selectively build it.

**Comment by Anachron** [comment]
Sure, but wouldnt it make more sense to make the sizing equal so its uniform?

So we have two nav dropdown styles, both fitting the link dimensions.

**Comment by Anachron** [comment]
Thanks for the fix, that looks much better!

**Comment by lucaslarroche** [comment]
@Anachron, 
I committed some style changes for the Dropdown.
I still think the default dropdown's size is the correct one. It's the same size and style as the `<select>`. It makes sense, it's consistent.
On the other hand, I listened to your remarks: dropdowns inside a `<nav>` are now the same size as the links.
Preview: https://picocss.github.io/pico/docs/dropdowns.html

**Comment by Anachron** [comment]
Yep, already saw and I agree that the current dropbox from this PR looks ready to ship.

**Comment by Anachron** [comment]
Just a minor nitpick: On `FF desktop linux 96.0.2 (64-Bit)` the dropdown selects "dropdown menu" is slighty smaller than the button. 

Sorry for just telling you know, I had no chance to test it on desktop before. Everything else is as expected.

**Comment by lucaslarroche** [comment]
@Anachron, I tested on Firefox MacOs and I don't see any problem.
Can you make a screenshot?

**Comment by Anachron** [comment]
I'll try to make a screenshot later today. Sorry for the delay

**Comment by lucaslarroche** [comment]
@Anachron, 
No worries.
I will - finally - publish this release.
We will publish a patch later if needed.

**Pull request merged**
