### PR TITLE
add issue templates

### LINKED ISSUE #89: enhancement: add issue templates
Hey

This is an ever-growing repository, it will keep having feature requests and PRs and the never-ending process.

We could add issue templates similar to [this](https://github.com/picocss/pico/issues/88). 
- Easy for the maintainer, not to ask for more details.
- Could ask the issue reporter for a potential fix.
- Since, we have feature_request, bug_report - we could have multiple templates.
- Including PR templates - what was fixed, issue number, any further lookouts?

Let me know, I would love to create a PR for the same.

### PR DESCRIPTION
**Pull request by tusharnankani**
Closes #89 

Looks like:

image

## Bug Report

image

## Feature Request 

image

### CODE REVIEW

**Comment by tusharnankani** [comment]
Any updates @lucaslarroche

**Comment by lucaslarroche** [comment]
Hi @tusharnankani, 

Sorry for the delay.
I finally looked into [issue templates ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

I think this PR could be the occasion to move the [Contributing README section](https://github.com/picocss/pico#contributing) into a proper [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) file.

Also, we might want to introduce some "Prerequisites" and operating system/browser selectors like in [Boostrap issue templates](https://github.com/twbs/bootstrap/tree/main/.github/ISSUE_TEMPLATE).

The templates are an important addition because indeed, I'm starting to get a little overwhelmed with the volume of work to maintain Pico 🙂.

**Comment by tusharnankani** [comment]
> I think this PR could be the occasion to move the Contributing README section into a proper CONTRIBUTING.md file.

Yes!
I'll add it.

> Also, we might want to introduce some "Prerequisites" and operating system/browser selectors like in Boostrap issue templates.

So essentially [this](https://github.com/twbs/bootstrap/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml) is using GitHub Issue **Forms**. Let me know if you want those?

**Comment by tusharnankani** [comment]
I have created CONTRIBUTING.md
I did not make any changes to README, you might want to change it according to your needs.

**Comment by lucaslarroche** [comment]
Hi @tusharnankani,

Again, thank you very much.
I finally took the time to edit the templates.
I mainly made changes to move help requests and feature requests to the GitHub Discussions tab.

I have chosen not to implement GitHub Issue Forms at this time.

I have already merged these modifications to `master` to test that everything works well. #176
I made some additional changes that I will merge in the [next release](https://github.com/picocss/pico/pull/155).

**Pull request merged**
