### PR TITLE
Update _form.scss

### PR DESCRIPTION
**Pull request by DavidSouther**
vertical-align only applies to inline-level elements

https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align
https://drafts.csswg.org/css2/#propdef-vertical-align

### CODE REVIEW

**Comment by lucaslarroche** [comment]
@DavidSouther, thank you.
I just did some tests, and it seems to me that this property is no longer useful. I would be for removing it.

```Diff
input:not([type="checkbox"]):not([type="radio"]):not([type="range"]):not([type="file"]),
select,
textarea {
  appearance: none;
  padding: var(--form-element-spacing-vertical) var(--form-element-spacing-horizontal);
- vertical-align: middle;
}
```
Any thought?

**Comment by DavidSouther** [comment]
Sounds fine to me. If you really wanted to reset and normalize, I think `baseline` would be most appropriate, but I agree that it doesn't look like it matters.

**Comment by lucaslarroche** [comment]
Looking at [Sanitize.css](https://github.com/csstools/sanitize.css/blob/main/forms.css), they don't reset the `vertical-align` property. We probably don't need it.

**Comment by DavidSouther** [comment]
Updated this PR to nix the property entirely.

**Pull request merged**
