### PR TITLE
Add dropdown navigation per #85

### PR DESCRIPTION
**Pull request by ethanpil**
Per the discussion in #85 here is a proposed solution. I tested it with the default [example file](https://github.com/picocss/examples/blob/master/preview/index.html) by adding this code right after the first `<main class="container">` tag:

```
 <!-- Nav with Dropdown -->
<section id="nav-with-dropdown">
        <h2>Nav with Dropdown</h2>
        <nav>
          <ul>
            <li><a href="#">Computers</a></li>
            <li><a href="#">Tablets</a></li>
            <li>
              <a href="#">Phones</a>
              <ul>
                <li><a href="#">Apple</a></li>
                <li><a href="#">Samsung</a></li>
                <li><a href="#">Google</a></li>
                <li><a href="#">Sony</a></li>
              </ul>
            </li>
            <li><a href="#">Accessories</a></li>
          </ul>
        </nav>
      </section>
```

### CODE REVIEW

**Comment by lucaslarroche** [comment]
Hi @ethanpil, 
I will review and merge it.
Probably this weekend. At worst the next.

**Comment by lucaslarroche** [comment]
Hi @ethanpil,

I like this addition, but there are a few problems:
- The Dropdown can't be transparent as we can have other elements below. Actually, to manage properly the overlay, we probably need a `box-shadow` too
- The submenu should be left-aligned to the parent link (and right-aligned in [`ltr` mode](https://picocss.com/docs/rtl.html))
- This feature should work on vertical nav (see `<aside>` in the [doc](https://picocss.com/docs/navs.html))
- Paddings should be a multiple of the CSS var `var(--spacing)`
- The `font-size` should probably stay at `1rem`
- We need to upgrade the documentation

I appreciate your PR, but I'd rather ship a more complete feature.
There is no emergency.

**Comment by ethanpil** [comment]
Good points @lucaslarroche 
Give me a few days and I will work on it.

**Comment by jubishop** [comment]
Thanks @ethanpil!  I will greatly appreciate this addition

**Comment by lucaslarroche** [comment]
@ethanpil
Yes, you are right. With a `border` and `box-shadow`, we should have some paddings. 
Screen-Shot-2022-01-10-at-10 13 06

Probably `calc(var(--spacing) * 0.5)`

**Comment by ethanpil** [comment]
@lucaslarroche  I just pushed in the changes you requested above. I built the css and replicated my results in [this JSFiddle](https://jsfiddle.net/ethanpil/xja0nug7/).

**Comment by lucaslarroche** [comment]
Hi @ethanpil,

Thank you.
I don't have time to do a proper review this week. It will probably be next week.
I don't want to rush too much on a non-mandatory feature. 
I preferred to concentrate on the [fixes](https://github.com/picocss/pico/pull/113) as it impacts all Pico users.

**Comment by lucaslarroche** [comment]
Hi @ethanpil, 

After more thinking, researching, and iterating on @KiranMantha's [PR](https://github.com/picocss/pico/pull/86), I changed the Dropdown integration.

Unfortunately, the [next minor release (1.5.0)](https://github.com/picocss/pico/pull/155) will not include your PR.

I think it's better for Pico's evolution as:
- Dropdowns work inside and outside the `<nav>` component
- Dropdowns can be styled as `<button>`
- Using `<details>` allows us to trigger Dropdowns `onclick` even without JavaScript (and not just on `hover`)

Preview is here: https://picocss.github.io/pico/docs/dropdowns.html

Feel free to review and comment.
Thank you for your contribution.

**Comment by jubishop** [comment]
Thanks Lucas!  It'll be worth the wait :)

**Comment by ethanpil** [comment]
@lucaslarroche I agree that @KiranMantha has a more flexible and robust solution. Glad that its there and happy to see the functionality in production ASAP!

**Comment by Anachron** [comment]
Looks good!

Just a little heads up:
The nav dropdown has a bad newline wrap, which the "li role=list" doesnt have.

FF Mobile, 97.2.0 (Build #2015863827)

**Pull request closed without merging**
