### PR TITLE
Feature: Dropdown

### PR DESCRIPTION
**Pull request by lucaslarroche**
**This PR deploy a Dropdown menu and a custom select**

Original PR, by @KiranMantha: #86
Issue: #52

### CODE REVIEW

**Comment by lucaslarroche** [comment]
@KiranMantha, 

Sorry, I messed up with [your PR](https://github.com/picocss/pico/pull/86) and the `dev` branch.
I wanted to keep your PR as is and open a new PR with my proposed changes and I merged your PR into `dev`.
To keep this feature isolated until the final merge I created a new `dev` branch.
😬

**Comment by KiranMantha** [comment]
@lucaslarroche 😄 sure

**Comment by lucaslarroche** [comment]
@KiranMantha 
```SCSS
details[open] {
    summary {
      &::before {
        display: block;
        z-index: 1;
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: transparent;
        content: '';
        cursor: default;
      }
    }
  }
```
Nice trick fo the close behavior 🙂

**Comment by lucaslarroche** [comment]
Preview (dark):

image

Preview (light): 

image

**Comment by KiranMantha** [comment]
@lucaslarroche this looks really cool. With anchor tags, this can be used for navigation also

**Comment by lucaslarroche** [comment]
@KiranMantha
My main changes from your [initial PR](https://github.com/picocss/pico/pull/86) are:
- Allowing the Dropdown to be used without radio buttons or checkboxes
- Allowing the `<summary>` element to be used with `role="button"`

Feel free to review this code and suggest edits.
I will keep this PR open for another week to allow other contributors to comment.
We might also need more CSS vars (`--dropdown-border-color`, etc.).

**Comment by KiranMantha** [comment]
I'm happy on how this is going. This now got a broad range of use cases. Others can use this 
1. As a part of navigation in their templates
2. As a form control

**Comment by jubishop** [comment]
> I'm happy on how this is going. This now got a broad range of use cases. Others can use this 
> 
> 1. As a part of navigation in their templates
> 
> 2. As a form control

Could we have an example of how to use in navigation?

**Comment by KiranMantha** [comment]
@jubishop , please find the example implementation [here](https://stackblitz.com/edit/web-platform-vz6n19?file=styles.css)

@lucaslarroche in above example i modified styles for dropdown especially when inside `nav` tag. please check once.

**Comment by KiranMantha** [comment]
> Hi, just curious whether there is any plan for autocomplete input (or even datalist). I am using Pico in my project which uses ajax hints for input autocomplete. But unfortunately it seems very difficult and big task to implement this input functionality to be on par with the highest CSS Pico standard :-)

@kvetoslavnovak can you provide a demo link?? i can see to atleast provide the generic styling..

**Comment by kvetoslavnovak** [comment]
This is my template. https://svelte.dev/repl/5734f123973d4682978427024ca90850?version=3.29.0
I am using SvelteKit so you can see style/css easily. Main functional changes were to change App.svelte```#autocomplete-items-list``` styles by adding ```position: absolute;``` and  delete ```top: 0;``` so the :"drop-down hints" does not push the rest of the page down but rather overlays it. The rest is to halve it "Pico" style which is not as easy for me.
Now I am focusing on ajax functionality to fetch hints form a server.

**Comment by kvetoslavnovak** [comment]
I had time to play with  it a  little bit. Here is updated example with Pico minified css included. 
https://svelte.dev/repl/4f80e2afb28647d8b0d5eeb77d3a362c?version=3.29.0
Just wait a moment, REPL is checking unused styles and a console will complain about them. But it works after a few seconds.

**Comment by lucaslarroche** [comment]
Hi @KiranMantha, 

I finally merged the Dropdown in the open PR for the [next minor release (1.5.0)](https://github.com/picocss/pico/pull/155).
Sorry for the delay. I'm a little overwhelmed by notifications and maintenance work on Pico.

Preview is here: https://picocss.github.io/pico/docs/dropdowns.html
Feel free to review and comment in [this PR](https://github.com/picocss/pico/pull/155).

**Comment by lucaslarroche** [comment]
Hi @kvetoslavnovak, 

I don't plan to support autocomplete now, and probably not in the future either, as it requires JavaScript.
Datalist is great, very semantic, but unfortunately, it's almost impossible to override the browsers' default styles.

Thanks for your example. 
Take a look at the new [Dropdown's preview](https://picocss.github.io/pico/docs/dropdowns.html). It could be helpful for your JavaScript autocomplete library.

**Comment by Anachron** [comment]
Looks good!

Just a little heads up:
The nav dropdown has a bad newline wrap, which the "li role=list" doesnt have.

FF Mobile, 97.2.0 (Build #2015863827)

**Comment by KiranMantha** [comment]
> Hi @KiranMantha,
> 
> I finally merged the Dropdown in the open PR for the [next minor release (1.5.0)](https://github.com/picocss/pico/pull/155). Sorry for the delay. I'm a little overwhelmed by notifications and maintenance work on Pico.
> 
> Preview is here: https://picocss.github.io/pico/docs/dropdowns.html Feel free to review and comment in [this PR](https://github.com/picocss/pico/pull/155).

Thankyou so much @lucaslarroche. Gald that my contribution is going to help others to build great templates 😄 💥

**Comment by kvetoslavnovak** [comment]
> Hi @kvetoslavnovak,
> 
> I don't plan to support autocomplete now, and probably not in the future either, as it requires JavaScript. Datalist is great, very semantic, but unfortunately, it's almost impossible to override the browsers' default styles.
> 
> Thanks for your example. Take a look at the new [Dropdown's preview](https://picocss.github.io/pico/docs/dropdowns.html). It could be helpful for your JavaScript autocomplete library.

This is perfectly fine. Dropdown proposal was a great start for me to make my own custom autocomplete input. I admire the Pico CSS as a basic not bloated system to build upon. 

I agree that datalist is  not very styling friendly, on mobile (iPhone) rather nightmare to use.

**Pull request merged**
