### PR TITLE
Add input-group and button-group

### PR DESCRIPTION
**Pull request by reinerBa**
As suggested in issue #159 . The code needs his own file because margin-bottom of inputs is set in the input file, which is parsed after the _button.scss

### CODE REVIEW

**Comment by reinerBa** [comment]
> With the way that the buttons currently handle `border-radius`, you end up with funny-looking buttons side-by-side:
> 
> https://jsfiddle.net/leoherzog/arux1js6/

Thanks for your Feedback ✌ and your friendly recommendation but for me it works fine when i use "SCSS" als styling language. 
image

**Comment by yus-ham** [comment]
maybe consider to use `role=group`

**Comment by lucaslarroche** [comment]
@reinerBa,
Thank you for this new contribution, and sorry for the delay.

### role="group"
As suggested by @yus-ham, I would prefer to use `role="group"` instead of `class="button-group"`.
It seems to fit perfectly in our case ([documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/group_role)).

```HTML
<div role="group">
  <button>Option 1</button>
  <button>Option 2</button>
  <button>Option 3</button>
</div>
```

It would also allow us not to have 2 different classes ` .button-group` and `.input-group`.

### aria-current

With version 1.5.0 we added the `aria-current` support.
Nothing to do here as it's already working if you rebase your branch from `master`.

```HTML
<div role="group">
  <button aria-current="page">Option 1</button>
  <button>Option 2</button>
  <button>Option 3</button>
</div>
```

### Architecture

I would suggest `components/group` instead of `content/form-input-group`.

**Comment by lucaslarroche** [comment]
Sorry, closed by mistake

**Comment by lucaslarroche** [comment]
@reinerBa, I'm closing this PR because this feature has been added to the `v2` (#261).

**Pull request closed without merging**
