### PR TITLE
Perf: Simpler/smaller selectors with :where :is

### PR DESCRIPTION
**Pull request by leomp12**
Note: https://developer.mozilla.org/en-US/docs/Web/CSS/:where#browser_compatibility doesn't match current [browserlist](https://github.com/picocss/pico/blob/master/package.json#L98-L102) entirely, I will continue the PR checking same microoptin on other files if you agree we can avoid fully supporting following browsers:

```
- Safari 13.1             0.530%
- Samsung 14.0            2.258%
- Samsung 13.0            0.198%
- Internet Explorer 11    0.748% (just mentioning, not supported already as it can't handle CSS props)
```

Ref.: https://browserslist.dev/?q=Pj0gMC41JSwgbGFzdCAyIG1ham9yIHZlcnNpb25zLCBub3QgZGVhZA%3D%3D

### CODE REVIEW

**Comment by lucaslarroche** [comment]
Hi @leomp12, 
Thank you.

I had never looked at the `:where` and `:is` selectors 😬 It's about time.

I noticed the `:where` usage in the [sanitize.css](https://github.com/csstools/sanitize.css) library. I was planning to update all the resets in Pico. But that's a lot of work since I decided to bring the resets component per component. We need to edit all the *.scss files.

Example [here](https://github.com/picocss/pico/blob/master/scss/content/_button.scss). The first 35 lines are the reset. Pico styles come after.

I believe these selectors can be helpful for [this](https://github.com/picocss/pico/blob/master/scss/content/_typography.scss#L163) too (which compile into a very very long selector [here](https://github.com/picocss/pico/blob/master/css/pico.css#L746).

And there are also probably quite a few changes to be made in those files as well: [_form-alt-input-types.scss](https://github.com/picocss/pico/blob/master/scss/content/_form-alt-input-types.scss) and [_form-checkbox-radio.scss](https://github.com/picocss/pico/blob/master/scss/content/_form-checkbox-radio.scss).

TBH, browser compatibility has not been tested extensively.
Related issue / discussion here: #76

I would love to ship these changes and it's probably necessary because Pico is starting to get heavy with all those complex selectors.

For consistency, if we make these changes, I would prefer that it be applied wherever possible.
I would love to have some help.

I could take care of all the resets.

Any thoughts?

**Comment by leomp12** [comment]
Hey @lucaslarroche ,

> I noticed the :where usage in the [sanitize.css](https://github.com/csstools/sanitize.css) library. I was planning to update all the resets in Pico.

great!

> very very long selector [here](https://github.com/picocss/pico/blob/master/css/pico.css#L746).

wow, i hadn't seen this one yet 😄 

> For consistency, if we make these changes, I would prefer that it be applied wherever possible.
I would love to have some help.

yup, i will keep working on it.

**Comment by lucaslarroche** [comment]
@leomp12, 
Thank you.
I improved many more selectors following your idea.
Your contribution will be merged in the [next release](https://github.com/picocss/pico/pull/155).

**Comment by leomp12** [comment]
Hey bud @lucaslarroche ,
Sorry for the delay, I haven't had (any) time lately 😬 

> Thank you.
I improved many more selectors following your idea.

Awesome, you're welcome 👍🏾

**Pull request merged**
