### PR TITLE
remove use of `.secondary` and `.contrast` from classless css

### PR DESCRIPTION
**Pull request by jubishop**
I noticed these in the classless css file, but these should not be referenced or used at all in classless.

### CODE REVIEW

**Comment by jubishop** [comment]
sorry for the sloppy commit history here, I created the changes on master then realized they should be coming in on top of dev.

**Comment by lucaslarroche** [comment]
Hi @jubishop, 

This deletion should only impact the **classless** version. 
What you are proposing would also impact the **standard** version.

We can use this variable to achieve the results you want:
```SCSS
@if $enable-classes {
  &.secondary,
  &.contrast {
    ...
  }
}
```

Example here: 
https://github.com/picocss/pico/blob/master/scss/content/_button.scss#L115

The variable is defined here:
https://github.com/picocss/pico/blob/master/scss/_variables.scss#L24

**Comment by jubishop** [comment]
That's what I'm doing (using that variable).  What am I missing?

**Comment by jubishop** [comment]
Oh I think so many files are changed because I didn't rerun the build process after merging in dev.  I'll update accordingly.

**Comment by jubishop** [comment]
wow ok I'm in git hell now.  this is a simple change I'm going to start over

**Pull request closed without merging**
