### PR TITLE
feat: add $semantic-root-element variable

### LINKED ISSUE #13: Built in padding doesn't apply in React (or Next.js).
I want to begin by saying that I love this project. It looks great, and it's really easy to use.

Unfortunately, I've found a bug.

In both [React](https://reactjs.org/) and [Next.js](https://nextjs.org/), all content is placed inside a wrapper `<div>` inside `<body>`.

For example:

```html

<!-- React -->

<body>
  <div id="root">
    <!-- all content goes here -->
  </div>
</body>

<!-- Next.js -->

<body>
  <div id="__next">
    <!-- all content goes here -->
  </div>
</body>

```

This breaks the responsive vertical padding on `<header>`, `<main>`, and `<footer>`, as defined [here](https://picocss.com/docs/#containers) in the documentation, and [here](../blob/master/scss/layout/_sectioning.scss#L21) in the source code.

The fix for this is pretty simple, but it involves putting edge cases for React and Next.js into the framework, which might be something you don't want to do.

I'm proposing changing this part of `layout/_sectioning.scss` (line 21):

```scss
body {
  // ...
}
```

to this:

```scss
body, #__next, #root {
  // ...
}
```

Of course, the CSS version of the framework would also need to be updated.

I'm currently using [patch-package](https://www.npmjs.com/package/patch-package) to make these patches in my own project.

I'm ready to make a pull request if you'd be happy with it, but if not, that's fine too.

### PR DESCRIPTION
**Pull request by ja1den**
This PR adds a variable for setting the semantic root element, which should allow for easy integration with frameworks that do not place content directly inside `<body>` (such as React, Next.js, and Nuxt).

For example, to integrate with Next.js, you'd set `$semantic-root-element` to `#__next`.

If you don't change `$semantic-root-element`, it will default to `body`, meaning everything will be the same as normal.

This PR will resolve #13 and possibly #222.

### CODE REVIEW

**Comment by lucaslarroche** [comment]
Sorry, closed by mistake

**Comment by lucaslarroche** [comment]
Hi @ja1den,
Thank you for this great addition, and sorry for the delay.
I'm going to merge into dev, then I'll merge into master quickly.

**Comment by weepy** [comment]
this is great - just what i needed for SvelteKit - how do I set this ?

**Comment by zachinglis** [comment]
> this is great - just what i needed for SvelteKit - how do I set this ?

Using this in SvelteKit happily. 

Import `SASS` like it says in the documentation: https://picocss.com/docs/customization.html

In `app.html` there is a bounding box that looks something like: ```<div>%sveltekit.body%</div>```, give it an ID. I chose 'root' for mine. So it looks like ```<div id="root">
			%sveltekit.body%
		</div>```

Then in your `SCSS` file should look something like this: ```$semantic-root-element: '#root';

@import "@picocss/pico/scss/pico";
```

And bingo! It works beautifully.

**Pull request merged**
